services:
  api:
    container_name: world-of-studies-api
    build:
      args:
        APP_PATH: ${API_PATH}
        PACKAGES_PATH: ${PACKAGES_PATH}
      context: .
      dockerfile: ${API_PATH}/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./${API_PATH}:/app/${API_PATH}
      - ./${API_TYPES_PATH}/dist:/app/${API_TYPES_PATH}/dist

  db:
    container_name: world-of-studies-db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword

  adminer:
    container_name: world-of-studies-adminer
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha


volumes:
  db-data:
  pgadmin-data:
