name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: UTC
  PORT: 3333
  HOST: 0.0.0.0
  LOG_LEVEL: info
  APP_KEY: testKey
  NODE_ENV: test
  DB_HOST: db
  DB_PORT: 5432
  DB_USER: dbuser
  DB_PASSWORD: dbpassword
  DB_DATABASE: mydb


jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
      with:
        version: 8.15.3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'
    - run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: actions/checkout@v3
    - run: pnpm lint:all

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: actions/checkout@v3
    - run: pnpm run test:all
