name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: UTC
  PORT: 3333
  HOST: 0.0.0.0
  LOG_LEVEL: info
  APP_KEY: testKeytestkeytestkey
  NODE_ENV: test
  DB_CONNECTION: sqlite
  DB_HOST: db
  DB_PORT: 5432
  DB_USER: dbuser
  DB_PASSWORD: dbpassword
  DB_DATABASE: mydb

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps: 
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint all files
        run: pnpm lint:all

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps: 
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test all apps
        run: pnpm run test:all
